const FETCH_USER='FETCH_USER';
const SAVE_ENTERED_DETAILS='SAVE_ENTERED_DETAILS';
const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS';
const FETCH_USER_DATA='FETCH_USER_DATA';
export 
{ 
    FETCH_USER,
    SAVE_ENTERED_DETAILS,
    USER_LOGIN_SUCCESS,
    FETCH_USER_DATA
}